### ISSUE TITLE
Having trouble deploying to Web App 

### ISSUE THREAD

**Issue by ArnaudLiN7** [michalmar/openai-demos-bot-webapp#5]
Hi ! I followed your tutorial but I'm having trouble in the deployment part ? Do you have to fill in the deploymentTemplates and deploymentScripts ? 

Thank you

**Comment by michalmar** [comment]
The deployment templates & scripts are coming from the EchoBot - https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/typescript_nodejs/02.echo-bot. I don’t modify nor use theme here (should be probably removed). 

Setup to get this running is assumed to be manually provisioning the resources (Bot service, Web App, OpenAI service) in Azure portal.

**Comment by ArnaudLiN7** [comment]
Still no success haha, I created a Node - 16-lts Web App, with Linux and deployed my code. But when I test the app with Bot Service it just does nothing. Are there more settings to specify for the Web App to work ?

**Comment by michalmar** [comment]
Does it work locally ? If so, does that run in webchat (in portal on botservice)? 

Usual things to check:
- app service has all environmental variables set up (configuration)
- AAD application - you set up password, also the app needs to be multi tenant

**Comment by ArnaudLiN7** [comment]
It does work locally but not in webchat.

Which env variables are required in the web app ? I have specified WEBSITE_NODE_DEFAULT_VERSION but nothing else.

Sorry for bothering you, I'm pretty new to this

EDIT: Everything's fine, It was just some stupid shenanigans with the App Id and Password.
